/** Texto alternativo de cada captura, con las mismas claves que la galería compartida. */
export const galleryAlt: Record<string, string> = {
  "005": "Listado de exámenes con sus estados de publicación y finalización",
  "006": "Confirmación para eliminar un examen",
  "007": "Creación de un examen y configuración de su navegación",
  "011": "Creación de usuarios con roles específicos por examen",
  "012": "Búsqueda de usuarios existentes",
  "019": "Administración de secciones del examen",
  "023": "Listado de casos clínicos y asignación de evaluadores",
  "028": "Creación de preguntas con imágenes adjuntas",
  "032": "Listado de tablas de cotejo",
  "034": "Creación de una tabla de cotejo con secciones e ítems puntuados",
  "038": "Biblioteca de recursos del examen con carga de documentos",
  "044": "Tablero de avance de las correcciones por evaluador",
  "049": "Disponibilidad de reportes antes de finalizar el examen",
  "052": "Bienvenida del estudiante e ingreso al examen",
  "053": "Ingreso del código de acceso al examen",
  "058": "Confirmación antes de comenzar el examen",
  "060": "Editor de respuestas con guardado automático",
  "063": "Confirmación para guardar y avanzar",
  "068": "Examen finalizado con descarga del reporte de respuestas",
  "070": "Pantalla de bienvenida del evaluador",
  "074": "Caso asignado pendiente de evaluación",
  "075": "Avance de la corrección por pregunta",
  "076": "Cola de corrección de estudiantes identificados por seudónimo",
  "078": "Aprobación conjunta de los ítems de la tabla de cotejo",
  "079": "Rechazo conjunto de los ítems de la tabla de cotejo",
  "086": "Corrección finalizada y descarga de su reporte",
  "090": "Chequeos de salud de base de datos, caché y colas",
  "001":
    "Pantalla de inicio de sesión de Filomena, que pide un número de documento y una contraseña",
  "004": "Inicio del administrador con los pasos ordenados para preparar un examen",
  "015": "Importación por planilla, con zona de carga, descarga de plantilla y selector de rol",
  "026": "Banco de preguntas con escenarios clínicos, sus consignas y su orden",
  "029": "Editor de preguntas completado con un escenario clínico y la consigna asociada",
  "033":
    "Detalle de una tabla de cotejo con ítems puntuados y la pregunta a la que corresponde cada uno",
  "017": "Tabla de seudónimos numerados, con una marca sobre los que están en uso",
  "040":
    "Consola de administración del examen, con controles de inicio, cierre y defensa junto al monitoreo en vivo",
  "057": "Tarjeta de ingreso al examen con el código, el seudónimo asignado y las reglas",
  "059": "Examen en curso, en el caso uno, pregunta uno de siete, con el texto del escenario",
  "066":
    "Calculadora gestacional integrada al examen, con selector de fecha y las fechas que deriva",
  "043": "Monitoreo en vivo de estudiantes por seudónimo, con su progreso y un control de alerta",
  "045": "Medidores en tiempo real del avance de estudiantes y evaluadores durante un examen",
  "077":
    "Pantalla de corrección con la respuesta del estudiante junto a la tabla de cotejo que la puntúa",
  "051": "Página de reportes con cuatro exportaciones disponibles una vez finalizado el examen",
  "091": "Tablero de Grafana con chequeos de salud de servicios y conteos por modelo del examen",
};
